/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChapterIdMemberIdRouteImport } from './routes/$chapterId.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdMemberIdRoute = ChapterIdMemberIdRouteImport.update({
  id: '/$chapterId/$memberId',
  path: '/$chapterId/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$chapterId/$memberId': typeof ChapterIdMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$chapterId/$memberId': typeof ChapterIdMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$chapterId/$memberId': typeof ChapterIdMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$chapterId/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$chapterId/$memberId'
  id: '__root__' | '/' | '/$chapterId/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChapterIdMemberIdRoute: typeof ChapterIdMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$chapterId/$memberId': {
      id: '/$chapterId/$memberId'
      path: '/$chapterId/$memberId'
      fullPath: '/$chapterId/$memberId'
      preLoaderRoute: typeof ChapterIdMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChapterIdMemberIdRoute: ChapterIdMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
