const data = [
  'ad reprehenderit in dolor consectetur amet laborum ex excepteur magna commodo adipisicing eu reprehenderit occaecat officia cupidatat culpa sint dolore',
  'elit deserunt do nostrud dolor dolor velit qui ad sint mollit culpa exercitation commodo irure aliquip do nisi id amet sit nostrud laboris magna ex occaecat proident ex pariatur cupidatat enim aliquip magna ea sint incididunt enim consequat deserunt sint',
  'ex pariatur aliquip culpa Lorem do voluptate laborum ullamco excepteur do elit aliquip magna tempor consectetur culpa amet Lorem duis consequat culpa mollit et adipisicing duis laborum et nisi ea ullamco adipisicing ipsum exercitation magna commodo do deserunt aliquip eu eu reprehenderit anim sit deserunt aliquip pariatur proident occaecat ad eiusmod dolor anim id magna labore elit aliqua Lorem ad',
  'tempor duis nisi aliquip sit occaecat dolor occaecat ex eiusmod cillum excepteur ullamco est culpa cupidatat nostrud eu aliqua cupidatat quis amet commodo magna deserunt fugiat non non non aliquip veniam cillum qui non Lorem ipsum officia voluptate in veniam fugiat exercitation ex adipisicing sint ullamco anim cillum id mollit qui veniam laboris aliquip eiusmod minim esse laborum Lorem ut aute adipisicing mollit fugiat laborum non quis magna eu ea eiusmod et amet aliquip id ex ad Lorem mollit id',
  'id duis occaecat anim elit et do sint labore mollit cillum officia ad elit labore incididunt adipisicing occaecat occaecat ut commodo occaecat reprehenderit consequat commodo irure anim excepteur consectetur laborum dolore eu Lorem proident aute eiusmod deserunt non dolore Lorem sunt ullamco ullamco quis exercitation sint aliquip quis aliqua Lorem duis minim minim commodo in culpa amet aliqua voluptate incididunt veniam commodo ipsum laboris nisi laborum esse exercitation excepteur duis et quis magna aute consectetur commodo reprehenderit consequat commodo sint qui voluptate adipisicing excepteur qui nisi occaecat culpa sunt officia sit pariatur id enim Lorem amet adipisicing amet tempor voluptate',
];

export default data;
